# Generated by Django 5.0.4 on 2024-06-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='default_img/default_product.jpg', null=True, upload_to='all/image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='video',
            field=models.FileField(blank=True, default='default_img/default_video.mp4', null=True, upload_to='all/video'),
        ),
    ]
