# Generated by Django 5.0.4 on 2024-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_products_image_alter_products_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='all/video'),
        ),
    ]
